version: '3.8'

services:
  mvc-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
